name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ -d www ]; then
              cd www
            else
              mkdir -p www
              cd www
              git init
              git remote add origin https://github.com/elgboffel/the_poc.git
            fi
            git pull origin main
            docker-compose -f .docker/docker-compose.yml --env-file .env up --build -d

